require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe OrganizersController do

  # This should return the minimal set of attributes required to create a valid
  # Organizer. As you add validations to Organizer, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # OrganizersController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all organizers as @organizers" do
      organizer = Organizer.create! valid_attributes
      get :index, {}, valid_session
      assigns(:organizers).should eq([organizer])
    end
  end

  describe "GET show" do
    it "assigns the requested organizer as @organizer" do
      organizer = Organizer.create! valid_attributes
      get :show, {:id => organizer.to_param}, valid_session
      assigns(:organizer).should eq(organizer)
    end
  end

  describe "GET new" do
    it "assigns a new organizer as @organizer" do
      get :new, {}, valid_session
      assigns(:organizer).should be_a_new(Organizer)
    end
  end

  describe "GET edit" do
    it "assigns the requested organizer as @organizer" do
      organizer = Organizer.create! valid_attributes
      get :edit, {:id => organizer.to_param}, valid_session
      assigns(:organizer).should eq(organizer)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Organizer" do
        expect {
          post :create, {:organizer => valid_attributes}, valid_session
        }.to change(Organizer, :count).by(1)
      end

      it "assigns a newly created organizer as @organizer" do
        post :create, {:organizer => valid_attributes}, valid_session
        assigns(:organizer).should be_a(Organizer)
        assigns(:organizer).should be_persisted
      end

      it "redirects to the created organizer" do
        post :create, {:organizer => valid_attributes}, valid_session
        response.should redirect_to(Organizer.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved organizer as @organizer" do
        # Trigger the behavior that occurs when invalid params are submitted
        Organizer.any_instance.stub(:save).and_return(false)
        post :create, {:organizer => {}}, valid_session
        assigns(:organizer).should be_a_new(Organizer)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Organizer.any_instance.stub(:save).and_return(false)
        post :create, {:organizer => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested organizer" do
        organizer = Organizer.create! valid_attributes
        # Assuming there are no other organizers in the database, this
        # specifies that the Organizer created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Organizer.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => organizer.to_param, :organizer => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested organizer as @organizer" do
        organizer = Organizer.create! valid_attributes
        put :update, {:id => organizer.to_param, :organizer => valid_attributes}, valid_session
        assigns(:organizer).should eq(organizer)
      end

      it "redirects to the organizer" do
        organizer = Organizer.create! valid_attributes
        put :update, {:id => organizer.to_param, :organizer => valid_attributes}, valid_session
        response.should redirect_to(organizer)
      end
    end

    describe "with invalid params" do
      it "assigns the organizer as @organizer" do
        organizer = Organizer.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Organizer.any_instance.stub(:save).and_return(false)
        put :update, {:id => organizer.to_param, :organizer => {}}, valid_session
        assigns(:organizer).should eq(organizer)
      end

      it "re-renders the 'edit' template" do
        organizer = Organizer.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Organizer.any_instance.stub(:save).and_return(false)
        put :update, {:id => organizer.to_param, :organizer => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested organizer" do
      organizer = Organizer.create! valid_attributes
      expect {
        delete :destroy, {:id => organizer.to_param}, valid_session
      }.to change(Organizer, :count).by(-1)
    end

    it "redirects to the organizers list" do
      organizer = Organizer.create! valid_attributes
      delete :destroy, {:id => organizer.to_param}, valid_session
      response.should redirect_to(organizers_url)
    end
  end

end
